### ISSUE TITLE
拓扑无法联通。测试环境mininet。

### ISSUE THREAD

**Issue by allenxun** [China863SDN/DCFabric#1]
使用如下mininet脚本创建拓扑pingall之后指定节点无法连通。
from mininet.topo import Topo

class MyTopo( Topo ):
    "Simple topology example."

```
def __init__( self ):
    "Create custom topo."

    # Initialize topology
    Topo.__init__( self )

    # Add hosts and switches
    leftHost = self.addHost( 'h1' )
    rightHost = self.addHost( 'h2' )
    middleHost = self.addHost( 'h3' )
    leftSwitch = self.addSwitch( 's4' )
    rightSwitch = self.addSwitch( 's5' )
    middleSwitch = self.addSwitch('s6')

    # Add links
    self.addLink( leftHost, leftSwitch )
    self.addLink( leftSwitch, middleSwitch )
    self.addLink( middleSwitch, rightSwitch )
    self.addLink( rightSwitch, rightHost )
    self.addLink( middleHost, middleSwitch)
```

topos = { 'mytopo': ( lambda: MyTopo() ) }
具体流表信息如下：
**\* s4 ------------------------------------------------------------------------
NXST_FLOW reply (xid=0x4):
 cookie=0x0, duration=4.708s, table=0, n_packets=1, n_bytes=98, idle_timeout=100, hard_timeout=200, idle_age=1, priority=1,in_port=2,dl_dst=46:cf:b7:b8:c8:a4 actions=output:1
 cookie=0x0, duration=4.708s, table=0, n_packets=1, n_bytes=98, idle_timeout=100, hard_timeout=200, idle_age=1, priority=1,in_port=1,dl_dst=46:8b:29:f2:0d:dc actions=output:2
**\* s5 ------------------------------------------------------------------------
NXST_FLOW reply (xid=0x4):
 cookie=0x0, duration=1.707s, table=0, n_packets=1, n_bytes=98, idle_timeout=100, hard_timeout=200, idle_age=1, priority=1,in_port=2,dl_dst=46:8b:29:f2:0d:dc actions=output:1
 cookie=0x0, duration=1.707s, table=0, n_packets=1, n_bytes=98, idle_timeout=100, hard_timeout=200, idle_age=1, priority=1,in_port=1,dl_dst=d6:16:09:8a:44:9e actions=output:2
**\* s6 ------------------------------------------------------------------------
NXST_FLOW reply (xid=0x4):
 cookie=0x0, duration=1.71s, table=0, n_packets=1, n_bytes=98, idle_timeout=100, hard_timeout=200, idle_age=1, priority=1,in_port=2,dl_dst=46:8b:29:f2:0d:dc actions=output:3
 cookie=0x0, duration=1.71s, table=0, n_packets=2, n_bytes=196, idle_timeout=100, hard_timeout=200, idle_age=1, priority=1,in_port=3,dl_dst=d6:16:09:8a:44:9e actions=output:2
 cookie=0x0, duration=4.714s, table=0, n_packets=1, n_bytes=98, idle_timeout=100, hard_timeout=200, idle_age=1, priority=1,in_port=3,dl_dst=46:cf:b7:b8:c8:a4 actions=output:1
 cookie=0x0, duration=4.714s, table=0, n_packets=1, n_bytes=98, idle_timeout=100, hard_timeout=200, idle_age=1, priority=1,in_port=1,dl_dst=46:8b:29:f2:0d:dc actions=output:3

**Comment by yangleo** [comment]
从流表的情况来看是没有创建vlan通道的流表，可能有以下几个原因
1：mininet的版本，建议OF1.3的版本
2：如果使用mininet环境，config/sdn_controller.conf配置文件中的openstack_on的参数设置为0，auto_fabric 设置为1
另外，请帖一下控制器运行的日志

**Comment by lusipad** [comment]
补充一个坑:
在使用前, 最好先看下版本
mn --version

mininet从2.2.0开始正式支持openflow1.3 (#1)
根据我的测试, ubuntu14, 默认安装后, 使用apt-get install mininet的方式安装,版本是2.1.0的,不支持OpenFlow1.3
哪怕用命令指定了openflow1.3协议也不行. 而且没有任何提示...
例: mn --switch ovs,protocols=openflow13 

(#1) http://mininet.org/blog/2014/12/09/announcing-mininet-2-2-0/

**Comment by allenxun** [comment]
需要启动java的界面，应该是其中有一些应用，管理某些东西。现在已经可以用了。
谢谢各位支持。

**Comment by lusipad** [comment]
问题解决. 关闭issue
